services:
  db:
    image: postgres:latest
    container_name: bookshop_db
    restart: always
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
