name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  postgres: ^2.5.2
  dart_jsonwebtoken: ^2.5.0
  crypto: ^3.0.2
  faker: ^2.1.0
  http: ^1.3.0
  shelf_static: ^1.1.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
