apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop
  namespace: bookshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookshop
  template:
    metadata:
      labels:
        app: bookshop
    spec:
      containers:
        - name: bookshop
          image: ghcr.io/limerio/dart-web-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookshop-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bookshop-secrets
                  key: JWT_SECRET
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: HOST
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bookshop-config
                  key: PORT
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /api/books
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/books
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
